
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action SimulationAction;
	private global::Gtk.Action ModelAction;
	private global::Gtk.Action HelpAction;
	private global::Gtk.Action LoadModelAction;
	private global::Gtk.Action SaveModelAsAction;
	private global::Gtk.Action SaveResultsAsAction;
	private global::Gtk.Action NewModelAction;
	private global::Gtk.Action ExitSimulatorAction;
	private global::Gtk.Action ParametersAction;
	private global::Gtk.Action RunAction;
	private global::Gtk.Action AddEndNodeAction;
	private global::Gtk.Action AddNetworkNodeAction;
	private global::Gtk.Action AddServerNodeAction;
	private global::Gtk.Action AboutAction;
	private global::Gtk.Action AddLinkAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar2;
	private global::Gtk.HBox hbox2;
	private global::Gtk.VBox vbox2;
	private global::Gtk.Frame frame10;
	private global::Gtk.Alignment GtkAlignment;
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	private global::Gtk.TreeView treeview3;
	private global::Gtk.Label GtkLabel8;
	private global::Gtk.Frame frame11;
	private global::Gtk.Alignment GtkAlignment1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TreeView treeview4;
	private global::Gtk.Label GtkLabel9;
	private global::Gtk.VBox vbox5;
	private global::Gtk.Frame frame12;
	private global::Gtk.Alignment GtkAlignment2;
	private global::NetTrafficSimulator.EndNodeWidget endnodewidget2;
	private global::Gtk.Label GtkLabel13;
	private global::Gtk.HBox hbox9;
	private global::Gtk.Fixed fixed2;
	private global::Gtk.Button button18;
	private global::Gtk.Frame frame4;
	private global::Gtk.Alignment TheAlignment;
	private global::NetTrafficSimulator.PacketTraceWidget packettracewidget1;
	private global::Gtk.Label GtkLabel15;
	private global::Gtk.HBox hbox8;
	private global::Gtk.Fixed fixed4;
	private global::Gtk.Fixed fixed3;
	private global::Gtk.ProgressBar progressbar1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.SimulationAction = new global::Gtk.Action ("SimulationAction", global::Mono.Unix.Catalog.GetString ("Simulation"), null, null);
		this.SimulationAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Simulation");
		w1.Add (this.SimulationAction, null);
		this.ModelAction = new global::Gtk.Action ("ModelAction", global::Mono.Unix.Catalog.GetString ("Model"), null, null);
		this.ModelAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Model");
		w1.Add (this.ModelAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.LoadModelAction = new global::Gtk.Action ("LoadModelAction", global::Mono.Unix.Catalog.GetString ("Load model"), null, null);
		this.LoadModelAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Load model");
		w1.Add (this.LoadModelAction, null);
		this.SaveModelAsAction = new global::Gtk.Action ("SaveModelAsAction", global::Mono.Unix.Catalog.GetString ("Save model as"), null, null);
		this.SaveModelAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save model as");
		w1.Add (this.SaveModelAsAction, null);
		this.SaveResultsAsAction = new global::Gtk.Action ("SaveResultsAsAction", global::Mono.Unix.Catalog.GetString ("Save results as"), null, null);
		this.SaveResultsAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save results as");
		w1.Add (this.SaveResultsAsAction, null);
		this.NewModelAction = new global::Gtk.Action ("NewModelAction", global::Mono.Unix.Catalog.GetString ("New model"), null, null);
		this.NewModelAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New model");
		w1.Add (this.NewModelAction, null);
		this.ExitSimulatorAction = new global::Gtk.Action ("ExitSimulatorAction", global::Mono.Unix.Catalog.GetString ("Exit simulator"), null, null);
		this.ExitSimulatorAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit simulator");
		w1.Add (this.ExitSimulatorAction, null);
		this.ParametersAction = new global::Gtk.Action ("ParametersAction", global::Mono.Unix.Catalog.GetString ("Parameters"), null, null);
		this.ParametersAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Parameters");
		w1.Add (this.ParametersAction, null);
		this.RunAction = new global::Gtk.Action ("RunAction", global::Mono.Unix.Catalog.GetString ("Run"), null, null);
		this.RunAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Run");
		w1.Add (this.RunAction, null);
		this.AddEndNodeAction = new global::Gtk.Action ("AddEndNodeAction", global::Mono.Unix.Catalog.GetString ("Add end node"), null, null);
		this.AddEndNodeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add end node");
		w1.Add (this.AddEndNodeAction, null);
		this.AddNetworkNodeAction = new global::Gtk.Action ("AddNetworkNodeAction", global::Mono.Unix.Catalog.GetString ("Add network node"), null, null);
		this.AddNetworkNodeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add network node");
		w1.Add (this.AddNetworkNodeAction, null);
		this.AddServerNodeAction = new global::Gtk.Action ("AddServerNodeAction", global::Mono.Unix.Catalog.GetString ("Add server node"), null, null);
		this.AddServerNodeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add server node");
		w1.Add (this.AddServerNodeAction, null);
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction, null);
		this.AddLinkAction = new global::Gtk.Action ("AddLinkAction", global::Mono.Unix.Catalog.GetString ("Add link"), null, null);
		this.AddLinkAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add link");
		w1.Add (this.AddLinkAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("NetSimul");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='FileAction' action='FileAction'><menuitem name='LoadModelAction' action='LoadModelAction'/><menuitem name='SaveModelAsAction' action='SaveModelAsAction'/><menuitem name='SaveResultsAsAction' action='SaveResultsAsAction'/><menuitem name='NewModelAction' action='NewModelAction'/><menuitem name='ExitSimulatorAction' action='ExitSimulatorAction'/></menu><menu name='SimulationAction' action='SimulationAction'><menuitem name='ParametersAction' action='ParametersAction'/><menuitem name='RunAction' action='RunAction'/></menu><menu name='ModelAction' action='ModelAction'><menuitem name='AddEndNodeAction' action='AddEndNodeAction'/><menuitem name='AddNetworkNodeAction' action='AddNetworkNodeAction'/><menuitem name='AddServerNodeAction' action='AddServerNodeAction'/><menuitem name='AddLinkAction' action='AddLinkAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.vbox1.Add (this.menubar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame10 = new global::Gtk.Frame ();
		this.frame10.Name = "frame10";
		this.frame10.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame10.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.treeview3 = new global::Gtk.TreeView ();
		this.treeview3.WidthRequest = 200;
		this.treeview3.CanFocus = true;
		this.treeview3.Name = "treeview3";
		this.GtkScrolledWindow2.Add (this.treeview3);
		this.GtkAlignment.Add (this.GtkScrolledWindow2);
		this.frame10.Add (this.GtkAlignment);
		this.GtkLabel8 = new global::Gtk.Label ();
		this.GtkLabel8.Name = "GtkLabel8";
		this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Nodes</b>");
		this.GtkLabel8.UseMarkup = true;
		this.frame10.LabelWidget = this.GtkLabel8;
		this.vbox2.Add (this.frame10);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame10]));
		w6.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame11 = new global::Gtk.Frame ();
		this.frame11.Name = "frame11";
		this.frame11.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame11.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.treeview4 = new global::Gtk.TreeView ();
		this.treeview4.CanFocus = true;
		this.treeview4.Name = "treeview4";
		this.GtkScrolledWindow1.Add (this.treeview4);
		this.GtkAlignment1.Add (this.GtkScrolledWindow1);
		this.frame11.Add (this.GtkAlignment1);
		this.GtkLabel9 = new global::Gtk.Label ();
		this.GtkLabel9.Name = "GtkLabel9";
		this.GtkLabel9.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Links</b>");
		this.GtkLabel9.UseMarkup = true;
		this.frame11.LabelWidget = this.GtkLabel9;
		this.vbox2.Add (this.frame11);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame11]));
		w10.Position = 1;
		this.hbox2.Add (this.vbox2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox2]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.frame12 = new global::Gtk.Frame ();
		this.frame12.Name = "frame12";
		this.frame12.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame12.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.endnodewidget2 = new global::NetTrafficSimulator.EndNodeWidget ();
		this.endnodewidget2.Events = ((global::Gdk.EventMask)(256));
		this.endnodewidget2.Name = "endnodewidget2";
		this.GtkAlignment2.Add (this.endnodewidget2);
		this.frame12.Add (this.GtkAlignment2);
		this.GtkLabel13 = new global::Gtk.Label ();
		this.GtkLabel13.Name = "GtkLabel13";
		this.GtkLabel13.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>GtkFrame</b>");
		this.GtkLabel13.UseMarkup = true;
		this.frame12.LabelWidget = this.GtkLabel13;
		this.vbox5.Add (this.frame12);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.frame12]));
		w14.Position = 0;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		this.hbox9.Add (this.fixed2);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.fixed2]));
		w15.Position = 0;
		// Container child hbox9.Gtk.Box+BoxChild
		this.button18 = new global::Gtk.Button ();
		this.button18.CanFocus = true;
		this.button18.Name = "button18";
		this.button18.UseUnderline = true;
		this.button18.Label = global::Mono.Unix.Catalog.GetString ("Delete");
		this.hbox9.Add (this.button18);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.button18]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		this.vbox5.Add (this.hbox9);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox9]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		this.hbox2.Add (this.vbox5);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox5]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.frame4 = new global::Gtk.Frame ();
		this.frame4.Name = "frame4";
		this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame4.Gtk.Container+ContainerChild
		this.TheAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.TheAlignment.Name = "TheAlignment";
		this.TheAlignment.LeftPadding = ((uint)(12));
		// Container child TheAlignment.Gtk.Container+ContainerChild
		this.packettracewidget1 = new global::NetTrafficSimulator.PacketTraceWidget ();
		this.packettracewidget1.WidthRequest = 200;
		this.packettracewidget1.Events = ((global::Gdk.EventMask)(256));
		this.packettracewidget1.Name = "packettracewidget1";
		this.TheAlignment.Add (this.packettracewidget1);
		this.frame4.Add (this.TheAlignment);
		this.GtkLabel15 = new global::Gtk.Label ();
		this.GtkLabel15.Name = "GtkLabel15";
		this.GtkLabel15.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Packet traces</b>");
		this.GtkLabel15.UseMarkup = true;
		this.frame4.LabelWidget = this.GtkLabel15;
		this.hbox2.Add (this.frame4);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.frame4]));
		w21.PackType = ((global::Gtk.PackType)(1));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w22.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.fixed4 = new global::Gtk.Fixed ();
		this.fixed4.Name = "fixed4";
		this.fixed4.HasWindow = false;
		this.hbox8.Add (this.fixed4);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.fixed4]));
		w23.Position = 0;
		// Container child hbox8.Gtk.Box+BoxChild
		this.fixed3 = new global::Gtk.Fixed ();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		this.hbox8.Add (this.fixed3);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.fixed3]));
		w24.Position = 1;
		// Container child hbox8.Gtk.Box+BoxChild
		this.progressbar1 = new global::Gtk.ProgressBar ();
		this.progressbar1.Name = "progressbar1";
		this.hbox8.Add (this.progressbar1);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.progressbar1]));
		w25.Position = 2;
		this.vbox1.Add (this.hbox8);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox8]));
		w26.Position = 2;
		w26.Expand = false;
		w26.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 845;
		this.DefaultHeight = 577;
		this.Show ();
		this.LoadModelAction.Activated += new global::System.EventHandler (this.loadFromFileHandler);
		this.SaveModelAsAction.Activated += new global::System.EventHandler (this.OnSaveModelAsActionActivated);
		this.SaveResultsAsAction.Activated += new global::System.EventHandler (this.saveResultsHandler);
		this.NewModelAction.Activated += new global::System.EventHandler (this.newModelHandler);
		this.ExitSimulatorAction.Activated += new global::System.EventHandler (this.exitHandler);
		this.ParametersAction.Activated += new global::System.EventHandler (this.OnParametersMenuClick);
		this.RunAction.Activated += new global::System.EventHandler (this.OnRunMenuClick);
		this.AddEndNodeAction.Activated += new global::System.EventHandler (this.onAddNewEndNode);
		this.AddNetworkNodeAction.Activated += new global::System.EventHandler (this.onAddNetNode);
		this.AddServerNodeAction.Activated += new global::System.EventHandler (this.onAddServNode);
		this.AboutAction.Activated += new global::System.EventHandler (this.OnAboutActionActivated);
		this.AddLinkAction.Activated += new global::System.EventHandler (this.OnAddLinkActionActivated);
		this.button18.Clicked += new global::System.EventHandler (this.OnDeleteButtonClicked);
	}
}
