
// This file has been generated by the GUI designer. Do not modify.
namespace NetTrafficSimulator
{
	public partial class LinkResultWidget
	{
		private global::Gtk.VBox vbox7;
		private global::Gtk.HBox hbox19;
		private global::Gtk.Label label29;
		private global::Gtk.Label label35;
		private global::Gtk.HBox hbox20;
		private global::Gtk.Label label30;
		private global::Gtk.Label label36;
		private global::Gtk.HBox hbox21;
		private global::Gtk.Label label31;
		private global::Gtk.Label label37;
		private global::Gtk.HBox hbox22;
		private global::Gtk.Label label32;
		private global::Gtk.Label label38;
		private global::Gtk.HBox hbox23;
		private global::Gtk.Label label33;
		private global::Gtk.Label label39;
		private global::Gtk.HBox hbox24;
		private global::Gtk.Label label34;
		private global::Gtk.Label label40;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label label1;
		private global::Gtk.Label label7;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label label2;
		private global::Gtk.Label label8;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label label3;
		private global::Gtk.Label label9;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label label4;
		private global::Gtk.Label label10;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Label label5;
		private global::Gtk.Label label11;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Label label6;
		private global::Gtk.Label label12;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget NetTrafficSimulator.LinkResultWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "NetTrafficSimulator.LinkResultWidget";
			// Container child NetTrafficSimulator.LinkResultWidget.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox19 = new global::Gtk.HBox ();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.label29 = new global::Gtk.Label ();
			this.label29.Name = "label29";
			this.label29.LabelProp = global::Mono.Unix.Catalog.GetString ("Packets carried");
			this.hbox19.Add (this.label29);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.label29]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.label35 = new global::Gtk.Label ();
			this.label35.Name = "label35";
			this.label35.LabelProp = global::Mono.Unix.Catalog.GetString ("label35");
			this.hbox19.Add (this.label35);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.label35]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox7.Add (this.hbox19);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox19]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox20 = new global::Gtk.HBox ();
			this.hbox20.Name = "hbox20";
			this.hbox20.Spacing = 6;
			// Container child hbox20.Gtk.Box+BoxChild
			this.label30 = new global::Gtk.Label ();
			this.label30.Name = "label30";
			this.label30.LabelProp = global::Mono.Unix.Catalog.GetString ("Active time");
			this.hbox20.Add (this.label30);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.label30]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.label36 = new global::Gtk.Label ();
			this.label36.Name = "label36";
			this.label36.LabelProp = global::Mono.Unix.Catalog.GetString ("label36");
			this.hbox20.Add (this.label36);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.label36]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox7.Add (this.hbox20);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox20]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox21 = new global::Gtk.HBox ();
			this.hbox21.Name = "hbox21";
			this.hbox21.Spacing = 6;
			// Container child hbox21.Gtk.Box+BoxChild
			this.label31 = new global::Gtk.Label ();
			this.label31.Name = "label31";
			this.label31.LabelProp = global::Mono.Unix.Catalog.GetString ("Passive time");
			this.hbox21.Add (this.label31);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.label31]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox21.Gtk.Box+BoxChild
			this.label37 = new global::Gtk.Label ();
			this.label37.Name = "label37";
			this.label37.LabelProp = global::Mono.Unix.Catalog.GetString ("label37");
			this.hbox21.Add (this.label37);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.label37]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox7.Add (this.hbox21);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox21]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox22 = new global::Gtk.HBox ();
			this.hbox22.Name = "hbox22";
			this.hbox22.Spacing = 6;
			// Container child hbox22.Gtk.Box+BoxChild
			this.label32 = new global::Gtk.Label ();
			this.label32.Name = "label32";
			this.label32.LabelProp = global::Mono.Unix.Catalog.GetString ("Percentage time idle");
			this.hbox22.Add (this.label32);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.label32]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox22.Gtk.Box+BoxChild
			this.label38 = new global::Gtk.Label ();
			this.label38.Name = "label38";
			this.label38.LabelProp = global::Mono.Unix.Catalog.GetString ("label38");
			this.hbox22.Add (this.label38);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.label38]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox7.Add (this.hbox22);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox22]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox23 = new global::Gtk.HBox ();
			this.hbox23.Name = "hbox23";
			this.hbox23.Spacing = 6;
			// Container child hbox23.Gtk.Box+BoxChild
			this.label33 = new global::Gtk.Label ();
			this.label33.Name = "label33";
			this.label33.LabelProp = global::Mono.Unix.Catalog.GetString ("Data carried");
			this.hbox23.Add (this.label33);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox23 [this.label33]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox23.Gtk.Box+BoxChild
			this.label39 = new global::Gtk.Label ();
			this.label39.Name = "label39";
			this.label39.LabelProp = global::Mono.Unix.Catalog.GetString ("label39");
			this.hbox23.Add (this.label39);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox23 [this.label39]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox7.Add (this.hbox23);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox23]));
			w15.Position = 4;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox24 = new global::Gtk.HBox ();
			this.hbox24.Name = "hbox24";
			this.hbox24.Spacing = 6;
			// Container child hbox24.Gtk.Box+BoxChild
			this.label34 = new global::Gtk.Label ();
			this.label34.Name = "label34";
			this.label34.LabelProp = global::Mono.Unix.Catalog.GetString ("Data per time average");
			this.hbox24.Add (this.label34);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox24 [this.label34]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox24.Gtk.Box+BoxChild
			this.label40 = new global::Gtk.Label ();
			this.label40.Name = "label40";
			this.label40.LabelProp = global::Mono.Unix.Catalog.GetString ("label40");
			this.hbox24.Add (this.label40);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox24 [this.label40]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.vbox7.Add (this.hbox24);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox24]));
			w18.Position = 5;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Usage %");
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("label7");
			this.hbox1.Add (this.label7);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label7]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			this.vbox7.Add (this.hbox1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox1]));
			w21.Position = 6;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Data sent");
			this.hbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label2]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("label8");
			this.hbox2.Add (this.label8);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label8]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			this.vbox7.Add (this.hbox2);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox2]));
			w24.Position = 7;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Data lost");
			this.hbox3.Add (this.label3);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label3]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("label9");
			this.hbox3.Add (this.label9);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label9]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			this.vbox7.Add (this.hbox3);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox3]));
			w27.Position = 8;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Percentage data lost");
			this.hbox4.Add (this.label4);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label4]));
			w28.Position = 0;
			w28.Expand = false;
			w28.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("label10");
			this.hbox4.Add (this.label10);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label10]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			this.vbox7.Add (this.hbox4);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox4]));
			w30.Position = 9;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Percent data delivered");
			this.hbox5.Add (this.label5);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label5]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("label11");
			this.hbox5.Add (this.label11);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label11]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			this.vbox7.Add (this.hbox5);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox5]));
			w33.Position = 10;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Percent data lost - link not active");
			this.hbox6.Add (this.label6);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label6]));
			w34.Position = 0;
			w34.Expand = false;
			w34.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("label12");
			this.hbox6.Add (this.label12);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label12]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			this.vbox7.Add (this.hbox6);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox6]));
			w36.Position = 11;
			w36.Expand = false;
			w36.Fill = false;
			this.Add (this.vbox7);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
