
// This file has been generated by the GUI designer. Do not modify.
namespace NetTrafficSimulator
{
	public partial class LinkWidget
	{
		private global::Gtk.VBox vbox8;
		private global::NetTrafficSimulator.LinkParamWidget linkparamwidget1;
		private global::NetTrafficSimulator.LinkResultWidget linkresultwidget2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget NetTrafficSimulator.LinkWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "NetTrafficSimulator.LinkWidget";
			// Container child NetTrafficSimulator.LinkWidget.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.linkparamwidget1 = null;
			this.vbox8.Add (this.linkparamwidget1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.linkparamwidget1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.linkresultwidget2 = null;
			this.vbox8.Add (this.linkresultwidget2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.linkresultwidget2]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.Add (this.vbox8);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
