
// This file has been generated by the GUI designer. Do not modify.
namespace NetTrafficSimulator
{
	public partial class NetworkNodeResultWidget
	{
		private global::Gtk.VBox vbox5;
		private global::Gtk.HBox hbox8;
		private global::Gtk.Label label11;
		private global::Gtk.Label label20;
		private global::Gtk.HBox hbox9;
		private global::Gtk.Label label12;
		private global::Gtk.Label label21;
		private global::Gtk.HBox hbox10;
		private global::Gtk.Label label13;
		private global::Gtk.Label label22;
		private global::Gtk.HBox hbox11;
		private global::Gtk.Label label14;
		private global::Gtk.Label label23;
		private global::Gtk.HBox hbox12;
		private global::Gtk.Label label15;
		private global::Gtk.Label label24;
		private global::Gtk.HBox hbox13;
		private global::Gtk.Label label16;
		private global::Gtk.Label label25;
		private global::Gtk.HBox hbox14;
		private global::Gtk.Label label17;
		private global::Gtk.Label label26;
		private global::Gtk.HBox hbox17;
		private global::Gtk.Label label18;
		private global::Gtk.Label label27;
		private global::Gtk.HBox hbox18;
		private global::Gtk.Label label19;
		private global::Gtk.Label label28;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.NodeView nodeview1;
		private global::Gtk.Label GtkLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget NetTrafficSimulator.NetworkNodeResultWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "NetTrafficSimulator.NetworkNodeResultWidget";
			// Container child NetTrafficSimulator.NetworkNodeResultWidget.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Packets processed");
			this.hbox8.Add (this.label11);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label11]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("label20");
			this.hbox8.Add (this.label20);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label20]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox5.Add (this.hbox8);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox8]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Time waited");
			this.hbox9.Add (this.label12);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label12]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label21 = new global::Gtk.Label ();
			this.label21.Name = "label21";
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("label21");
			this.hbox9.Add (this.label21);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label21]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox5.Add (this.hbox9);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox9]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Percent time idle");
			this.hbox10.Add (this.label13);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label13]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label22 = new global::Gtk.Label ();
			this.label22.Name = "label22";
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("label22");
			this.hbox10.Add (this.label22);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label22]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox5.Add (this.hbox10);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox10]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Average wait time");
			this.hbox11.Add (this.label14);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label14]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.label23 = new global::Gtk.Label ();
			this.label23.Name = "label23";
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString ("label23");
			this.hbox11.Add (this.label23);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label23]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox5.Add (this.hbox11);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox11]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Packets dropped");
			this.hbox12.Add (this.label15);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.label15]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.label24 = new global::Gtk.Label ();
			this.label24.Name = "label24";
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString ("label24");
			this.hbox12.Add (this.label24);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.label24]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox5.Add (this.hbox12);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox12]));
			w15.Position = 4;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox ();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Percent packets dropped");
			this.hbox13.Add (this.label16);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.label16]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.label25 = new global::Gtk.Label ();
			this.label25.Name = "label25";
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString ("label25");
			this.hbox13.Add (this.label25);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.label25]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.vbox5.Add (this.hbox13);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox13]));
			w18.Position = 5;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox ();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Routing packets sent");
			this.hbox14.Add (this.label17);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label17]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.label26 = new global::Gtk.Label ();
			this.label26.Name = "label26";
			this.label26.LabelProp = global::Mono.Unix.Catalog.GetString ("label26");
			this.hbox14.Add (this.label26);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label26]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			this.vbox5.Add (this.hbox14);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox14]));
			w21.Position = 6;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox17 = new global::Gtk.HBox ();
			this.hbox17.Name = "hbox17";
			this.hbox17.Spacing = 6;
			// Container child hbox17.Gtk.Box+BoxChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Routing packets received");
			this.hbox17.Add (this.label18);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.label18]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.label27 = new global::Gtk.Label ();
			this.label27.Name = "label27";
			this.label27.LabelProp = global::Mono.Unix.Catalog.GetString ("label27");
			this.hbox17.Add (this.label27);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.label27]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			this.vbox5.Add (this.hbox17);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox17]));
			w24.Position = 7;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox18 = new global::Gtk.HBox ();
			this.hbox18.Name = "hbox18";
			this.hbox18.Spacing = 6;
			// Container child hbox18.Gtk.Box+BoxChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Percent processed routing packets");
			this.hbox18.Add (this.label19);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.label19]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox18.Gtk.Box+BoxChild
			this.label28 = new global::Gtk.Label ();
			this.label28.Name = "label28";
			this.label28.LabelProp = global::Mono.Unix.Catalog.GetString ("label28");
			this.hbox18.Add (this.label28);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.label28]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			this.vbox5.Add (this.hbox18);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox18]));
			w27.Position = 8;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nodeview1 = new global::Gtk.NodeView ();
			this.nodeview1.WidthRequest = 800;
			this.nodeview1.HeightRequest = 200;
			this.nodeview1.CanFocus = true;
			this.nodeview1.Name = "nodeview1";
			this.GtkScrolledWindow.Add (this.nodeview1);
			this.GtkAlignment.Add (this.GtkScrolledWindow);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel = new global::Gtk.Label ();
			this.GtkLabel.Name = "GtkLabel";
			this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Link usage</b>");
			this.GtkLabel.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel;
			this.vbox5.Add (this.frame1);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.frame1]));
			w31.Position = 9;
			this.Add (this.vbox5);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
