
// This file has been generated by the GUI designer. Do not modify.
namespace NetTrafficSimulator
{
	public partial class NetworkNodeWidget
	{
		private global::Gtk.VBox vbox6;
		private global::NetTrafficSimulator.NetworkNodeParamWidget networknodeparamwidget1;
		private global::NetTrafficSimulator.NetworkNodeResultWidget networknoderesultwidget1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget NetTrafficSimulator.NetworkNodeWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "NetTrafficSimulator.NetworkNodeWidget";
			// Container child NetTrafficSimulator.NetworkNodeWidget.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.networknodeparamwidget1 = null;
			this.vbox6.Add (this.networknodeparamwidget1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.networknodeparamwidget1]));
			w1.Position = 0;
			// Container child vbox6.Gtk.Box+BoxChild
			this.networknoderesultwidget1 = null;
			this.vbox6.Add (this.networknoderesultwidget1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.networknoderesultwidget1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.Add (this.vbox6);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
