
// This file has been generated by the GUI designer. Do not modify.
namespace NetTrafficSimulator
{
	public partial class LinkResultWidget
	{
		private global::Gtk.VBox vbox7;
		private global::Gtk.HBox hbox19;
		private global::Gtk.Label label29;
		private global::Gtk.Label label35;
		private global::Gtk.HBox hbox20;
		private global::Gtk.Label label30;
		private global::Gtk.Label label36;
		private global::Gtk.HBox hbox21;
		private global::Gtk.Label label31;
		private global::Gtk.Label label37;
		private global::Gtk.HBox hbox22;
		private global::Gtk.Label label32;
		private global::Gtk.Label label38;
		private global::Gtk.HBox hbox23;
		private global::Gtk.Label label33;
		private global::Gtk.Label label39;
		private global::Gtk.HBox hbox24;
		private global::Gtk.Label label34;
		private global::Gtk.Label label40;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget NetTrafficSimulator.LinkResultWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "NetTrafficSimulator.LinkResultWidget";
			// Container child NetTrafficSimulator.LinkResultWidget.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox19 = new global::Gtk.HBox ();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.label29 = new global::Gtk.Label ();
			this.label29.Name = "label29";
			this.label29.LabelProp = global::Mono.Unix.Catalog.GetString ("Packets carried");
			this.hbox19.Add (this.label29);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.label29]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.label35 = new global::Gtk.Label ();
			this.label35.Name = "label35";
			this.label35.LabelProp = global::Mono.Unix.Catalog.GetString ("label35");
			this.hbox19.Add (this.label35);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.label35]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox7.Add (this.hbox19);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox19]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox20 = new global::Gtk.HBox ();
			this.hbox20.Name = "hbox20";
			this.hbox20.Spacing = 6;
			// Container child hbox20.Gtk.Box+BoxChild
			this.label30 = new global::Gtk.Label ();
			this.label30.Name = "label30";
			this.label30.LabelProp = global::Mono.Unix.Catalog.GetString ("Packets dropped");
			this.hbox20.Add (this.label30);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.label30]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.label36 = new global::Gtk.Label ();
			this.label36.Name = "label36";
			this.label36.LabelProp = global::Mono.Unix.Catalog.GetString ("label36");
			this.hbox20.Add (this.label36);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.label36]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox7.Add (this.hbox20);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox20]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox21 = new global::Gtk.HBox ();
			this.hbox21.Name = "hbox21";
			this.hbox21.Spacing = 6;
			// Container child hbox21.Gtk.Box+BoxChild
			this.label31 = new global::Gtk.Label ();
			this.label31.Name = "label31";
			this.label31.LabelProp = global::Mono.Unix.Catalog.GetString ("Drop percentage");
			this.hbox21.Add (this.label31);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.label31]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox21.Gtk.Box+BoxChild
			this.label37 = new global::Gtk.Label ();
			this.label37.Name = "label37";
			this.label37.LabelProp = global::Mono.Unix.Catalog.GetString ("label37");
			this.hbox21.Add (this.label37);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.label37]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox7.Add (this.hbox21);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox21]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox22 = new global::Gtk.HBox ();
			this.hbox22.Name = "hbox22";
			this.hbox22.Spacing = 6;
			// Container child hbox22.Gtk.Box+BoxChild
			this.label32 = new global::Gtk.Label ();
			this.label32.Name = "label32";
			this.label32.LabelProp = global::Mono.Unix.Catalog.GetString ("Passive time");
			this.hbox22.Add (this.label32);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.label32]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox22.Gtk.Box+BoxChild
			this.label38 = new global::Gtk.Label ();
			this.label38.Name = "label38";
			this.label38.LabelProp = global::Mono.Unix.Catalog.GetString ("label38");
			this.hbox22.Add (this.label38);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.label38]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox7.Add (this.hbox22);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox22]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox23 = new global::Gtk.HBox ();
			this.hbox23.Name = "hbox23";
			this.hbox23.Spacing = 6;
			// Container child hbox23.Gtk.Box+BoxChild
			this.label33 = new global::Gtk.Label ();
			this.label33.Name = "label33";
			this.label33.LabelProp = global::Mono.Unix.Catalog.GetString ("Active time");
			this.hbox23.Add (this.label33);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox23 [this.label33]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox23.Gtk.Box+BoxChild
			this.label39 = new global::Gtk.Label ();
			this.label39.Name = "label39";
			this.label39.LabelProp = global::Mono.Unix.Catalog.GetString ("label39");
			this.hbox23.Add (this.label39);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox23 [this.label39]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox7.Add (this.hbox23);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox23]));
			w15.Position = 4;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox24 = new global::Gtk.HBox ();
			this.hbox24.Name = "hbox24";
			this.hbox24.Spacing = 6;
			// Container child hbox24.Gtk.Box+BoxChild
			this.label34 = new global::Gtk.Label ();
			this.label34.Name = "label34";
			this.label34.LabelProp = global::Mono.Unix.Catalog.GetString ("Percent time idle");
			this.hbox24.Add (this.label34);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox24 [this.label34]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox24.Gtk.Box+BoxChild
			this.label40 = new global::Gtk.Label ();
			this.label40.Name = "label40";
			this.label40.LabelProp = global::Mono.Unix.Catalog.GetString ("label40");
			this.hbox24.Add (this.label40);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox24 [this.label40]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.vbox7.Add (this.hbox24);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox24]));
			w18.Position = 5;
			w18.Expand = false;
			w18.Fill = false;
			this.Add (this.vbox7);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
