
// This file has been generated by the GUI designer. Do not modify.
namespace NetTrafficSimulator
{
	public partial class EndNodeWidget
	{
		private global::Gtk.VBox vbox9;
		private global::NetTrafficSimulator.EndNodeParamWidget endnodeparamwidget3;
		private global::NetTrafficSimulator.EndNodeEventsWidget endnodeeventswidget2;
		private global::NetTrafficSimulator.EndNodeResultWidget endnoderesultwidget3;
		private global::Gtk.HBox hbox24;
		private global::Gtk.Button button3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget NetTrafficSimulator.EndNodeWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "NetTrafficSimulator.EndNodeWidget";
			// Container child NetTrafficSimulator.EndNodeWidget.Gtk.Container+ContainerChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.endnodeparamwidget3 = new global::NetTrafficSimulator.EndNodeParamWidget ();
			this.endnodeparamwidget3.Events = ((global::Gdk.EventMask)(256));
			this.endnodeparamwidget3.Name = "endnodeparamwidget3";
			this.vbox9.Add (this.endnodeparamwidget3);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.endnodeparamwidget3]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.endnodeeventswidget2 = new global::NetTrafficSimulator.EndNodeEventsWidget ();
			this.endnodeeventswidget2.Events = ((global::Gdk.EventMask)(256));
			this.endnodeeventswidget2.Name = "endnodeeventswidget2";
			this.vbox9.Add (this.endnodeeventswidget2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.endnodeeventswidget2]));
			w2.Position = 1;
			// Container child vbox9.Gtk.Box+BoxChild
			this.endnoderesultwidget3 = new global::NetTrafficSimulator.EndNodeResultWidget ();
			this.endnoderesultwidget3.Events = ((global::Gdk.EventMask)(256));
			this.endnoderesultwidget3.Name = "endnoderesultwidget3";
			this.vbox9.Add (this.endnoderesultwidget3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.endnoderesultwidget3]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox24 = new global::Gtk.HBox ();
			this.hbox24.Name = "hbox24";
			this.hbox24.Spacing = 6;
			// Container child hbox24.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button ();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString ("Remove");
			this.hbox24.Add (this.button3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox24 [this.button3]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox9.Add (this.hbox24);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox24]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			this.Add (this.vbox9);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
